title: Sebastian Limbach
author: Sebastian Limbach
email: hello@sebastianlimbach.com
adress:
    street: Eichfeld 1a
    town: 53773 Hennef(Sieg), Deutschland

baseurl: ""
url: http://sebastianlimbach.com

repository:
    name: bastilimbach/bastilimbach.github.io
    url: https://github.com/bastilimbach/bastilimbach.github.io

twitter:
    username: bastilimbach
github:
    username: bastilimbach

analyticsID: UA-63161411-1

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .travis.yml
  - README.md
  - vendor
